# Generated by Django 3.2.12 on 2022-05-26 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_item_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_url',
            field=models.CharField(default='https://cdn.pixabay.com/photo/2019/09/08/17/24/eat-4461470_1280.png', max_length=10000),
        ),
    ]
